spring.application.name=DriveEasy-ServiceRegistry

# Eureka Server by default runs on port 8761
server.port=8761

# Configuration for Eureka Server (Service Registry)
# Eureka Server never registers itself in the Service Registry
eureka.client.register-with-eureka=false

# Eureka Server does not discover and fetch registry information from Service Registry
eureka.client.fetch-registry=false